---
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:ConfigData/
server:
  port: 8888
